"""Generate seed SQL for the tcg-insert-2026 promo campaign.

Codes are 8 chars, uppercase alphanumeric, with ambiguous characters removed
(no 0/1/I/L/O/S). 300 codes per the planned print run.
"""
import secrets
import sys

CHARS = "23456789ABCDEFGHJKMNPQRTUVWXYZ"  # no 0/1/I/L/O/S
LEN   = 8
N     = 300
CAMPAIGN = "tcg-insert-2026"
EXPIRES  = "2026-06-14"

def gen():
    return "".join(secrets.choice(CHARS) for _ in range(LEN))

codes = set()
while len(codes) < N:
    codes.add(gen())

codes = sorted(codes)
rows = [
    f"('{c}', '{CAMPAIGN}', 'buyer', 'fixed_amount', 1000, 10000, '{EXPIRES}')"
    for c in codes
]
sql = (
    f"-- Seed for {CAMPAIGN} campaign ({N} codes, 8-char alphanumeric, no ambiguous chars)\n"
    f"-- Generated by _gen_tcg_codes.py — re-running this migration is safe (INSERT OR IGNORE).\n"
    f"INSERT OR IGNORE INTO promo_codes (code, campaign, offer_type, discount_kind, discount_value, min_subtotal, expires_at) VALUES\n"
    + ",\n".join(rows)
    + ";\n"
)
sys.stdout.write(sql)
